<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NCSH5A8" failures="1" tests="7" name="Surefire test" time="6.563" errors="0" timestamp="2025-07-28T05:23:45 EEST">
  <testcase classname="TestCases" name="Login_test_TC_0001" time="0.826"/>
  <testcase classname="TestCases" name="Login_test_TC_0002" time="0.255"/>
  <testcase classname="TestCases" name="Login_test_TC_0003" time="0.253"/>
  <testcase classname="TestCases" name="Add_Record_TC_0004" time="0.262"/>
  <testcase classname="TestCases" name="Add_Record_TC_0005" time="0.125">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at TestCases.Add_Record_TC_0005(TestCases.java:112)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Add_Record_TC_0005 -->
  <testcase classname="TestCases" name="Edit_Record_TC_0006" time="0.211"/>
  <testcase classname="TestCases" name="Delete_Record_TC_0007" time="0.353"/>
</testsuite> <!-- Surefire test -->
